# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    include_format: false
  view:
    view_response_listener: true
    formats:
      json: true
      xml: true
  format_listener:
    rules:
    - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'json', prefer_extension: false }
  body_listener:
    enabled: true
  param_fetcher_listener:
    enabled: true